variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_REGISTRY: 662032419283.dkr.ecr.eu-north-1.amazonaws.com/homemap

stages:
  - build
  - api-test

before_script:
  - apk add --no-cache curl jq python3 py3-pip
  - pip install --break-system-packages awscli
  - aws ecr get-login-password | docker login --username AWS --password-stdin ${DOCKER_REGISTRY}

build:
  image:
    name: docker:27.3.1-alpine3.20
  services:
    - docker:27.3.1-alpine3.20
  only:
    - main
  script:
    - echo Building and tagging Docker images...
    - docker-compose -f docker-compose.yml -f docker-compose.prod.yml build
    - echo Pushing images to Amazon ECR...
    - docker-compose -f docker-compose.yml -f docker-compose.prod.yml push
  after_script:
    - docker logout ${DOCKER_REGISTRY}
  stage: build
  tags:
    - self-hosted

api-test:
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_TLS_CERTDIR: ""
  image:
    name: docker:27.3.1-alpine3.20
  services:
    - docker:27.3.1-alpine3.20
  only:
    - main
  script:
    - echo Testing API using Postman...
    - docker-compose -f docker-compose.yml -f docker-compose.prod.yml -f docker-compose.e2e.yml up --abort-on-container-exit --exit-code-from newman
    - echo Tearing donw containers with volumes...
    - docker-compose down -v
  after_script:
    - docker logout ${DOCKER_REGISTRY}
  stage: api-test
  tags:
    - self-hosted
