services:
  nuxt:
    container_name: nuxt-app
    restart: unless-stopped
    build:
      context: ./app
      target: dev
    ports:
      - 3000:3000
    volumes:
      - ./app:/app
      - node_modules:/app/node_modules
    env_file:
      - ./app/.env

volumes:
  node_modules:
