services:
  nuxt:
    build:
      target: dev
    ports:
      - 24678:24678
    env_file:
      - ./app/.env
    volumes:
      - ./app:/app
      - node_modules:/app/node_modules
  
  dotnet:
    build:
      target: dev
    ports:
      - 7185:7185
    volumes:
      - ./api:/app
      - ~/.aspnet/https:/https:ro
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    env_file:
      - ./api/.env

volumes:
  node_modules:
