services:
  nuxt:
    container_name: nuxt-app
    restart: unless-stopped
    build:
      context: ./app
      target: dev
    ports:
      - 3000:3000
      - 24678:24678
    volumes:
      - ./app:/app
      - node_modules:/app/node_modules
    env_file:
      - ./app/.env
  
  dotnet:
    container_name: dotnet-api
    restart: unless-stopped
    build:
      context: ./api
      target: dev
    ports:
      - 8080:8080
      - 7185:7185
    volumes:
      - ./api:/app
      - ~/.aspnet/https:/https:ro
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${HTTPS_CERTS_PASSWORD}

volumes:
  node_modules:
