services:
  newman:
    container_name: newman
    image: postman/newman:alpine
    network_mode: 'service:dotnet'
    volumes:
      - ./api/test/e2e:/etc/newman
    command: >
      run /etc/newman/homemap-e2e-tests.postman_collection.json \
        --environment /etc/newman/homemap_env.postman_environment.json
