services:
  nuxt:
    container_name: nuxt-app
    restart: unless-stopped
    build:
      context: ./app
    ports:
      - 3000:3000
    env_file:
      - ./app/.env
  
  dotnet:
    container_name: dotnet-api
    restart: unless-stopped
    build:
      context: ./api
    ports:
      - 8080:8080
    networks:
      - mq

  nanomq:
    container_name: nanomq-broker
    restart: unless-stopped
    image: emqx/nanomq:latest
    ports:
      - 1883:1883
      # - 8083:8083
      # - 8883:8883
    networks:
      - mq

networks:
  mq:
