services:
  nuxt:
    container_name: nuxt-app
    restart: unless-stopped
    build:
      context: ./app
  
  dotnet:
    container_name: dotnet-api
    restart: unless-stopped
    build:
      context: ./api
    volumes:
      - db_data:/app/data
    depends_on:
      - nanomq
    networks:
      - mq_net

  nanomq:
    container_name: nanomq-broker
    restart: unless-stopped
    image: emqx/nanomq:latest
    volumes:
      - ./nanomq.conf:/etc/nanomq.conf:ro
    networks:
      - mq_net

volumes:
  db_data:

networks:
  mq_net:
