services:
  nuxt:
    container_name: nuxt-app
    restart: unless-stopped
    build:
      context: ./app
      target: dev
    image: 662032419283.dkr.ecr.eu-north-1.amazonaws.com/homemap/front:latest
    ports:
      - 3000:3000
      - 24678:24678
    volumes:
      - ./app:/app
      - node_modules:/app/node_modules
    env_file:
      - ./app/.env
  
  dotnet:
    container_name: dotnet-api
    restart: unless-stopped
    build:
      context: ./api
      target: dev
    image: 662032419283.dkr.ecr.eu-north-1.amazonaws.com/homemap/back:latest
    ports:
      - 8080:8080
      - 7185:7185
    volumes:
      - ./api:/app
      - ~/.aspnet/https:/https:ro
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    env_file:
      - ./api/.env

  nanomq:
    container_name: nanomq-broker
    restart: unless-stopped
    image: emqx/nanomq:latest
    ports:
      - 1883:1883
      # - 8083:8083
      # - 8883:8883

volumes:
  node_modules:
